### ISSUE TITLE
Trying to load external modules defined in dependencies will lead to problems

### ISSUE THREAD

**Issue by christianvoigt** [benawad/typescript-yarn-workspace-example#1]
Hi, thanks for the example. However, I think it is incomplete. At the moment, trying to load dependencies saved in the workspace root node_modules folder will not work correctly in Typescript and VS Code (at least it does not for me). The module will not be found.

The example packages only define devDependencies for which these problems will not occur.

I had to install https://github.com/spion/typescript-workspace-plugin to getting things to work.
I think it would be a good idea to add this to the example to avoid some headaches for other people with these problems.

**Comment by benawad** [comment]
How can I replicate? I tried the following and it worked fine for me:

```
git clone https://github.com/benawad/typescript-yarn-workspace-example.git
cd typescript-yarn-workspace-example
yarn install
cd packages/common
yarn build
cd ../server
yarn add express
yarn add -D @types/express
yarn build
```

Did you build the common package? I think that may be your problem, this should work with 3rd party packages.

**Comment by christianvoigt** [comment]
Hi, I actually did not try it with the example packages. I tried it with my own packages. Sorry, it seems I was wrong and the problems were caused by something else (I had to add the types of one package to tsconfig.json and reload VS Code before they were found). 

The plugin author explained the need for his plugin here: https://github.com/Microsoft/TypeScript/issues/3469#issuecomment-341977362

> "What we don't have, and what the plugin I wrote provides, is a way to load all the sources at the same time. When I need to make changes to two or more modules at the same time, I don't want "go to definition" and "go to type definition" to send me to the .d.ts file. I want it to send me to the original source code location, so that perhaps I might edit it. Otherwise, I would just load the individual project directory and the node_modules symlinks created by lerna/yarn would just work."

So this seems unconnected to my problems (though useful nonetheless).
